from fastapi import APIRouter, HTTPException
from typing import List

from app.database import supabase
from app.schemas import EmployeeCreate, EmployeeUpdate, EmployeeOut

router = APIRouter(prefix="/employees", tags=["Employee Module"])


@router.post("/", response_model=EmployeeOut)
def create_employee(payload: EmployeeCreate):
    """Create a new employee. employee_id is auto-generated by the DB."""
    result = supabase.table("employees").insert(payload.model_dump()).execute()
    if not result.data:
        raise HTTPException(status_code=400, detail="Failed to create employee")
    return result.data[0]


@router.get("/", response_model=List[EmployeeOut])
def list_employees():
    """List all employees - used to populate the Update/Delete dropdowns."""
    result = (
        supabase.table("employees")
        .select("*")
        .order("name", desc=False)
        .execute()
    )
    return result.data


@router.get("/{employee_id}", response_model=EmployeeOut)
def get_employee(employee_id: int):
    result = (
        supabase.table("employees")
        .select("*")
        .eq("employee_id", employee_id)
        .execute()
    )
    if not result.data:
        raise HTTPException(status_code=404, detail="Employee not found")
    return result.data[0]


@router.put("/{employee_id}", response_model=EmployeeOut)
def update_employee(employee_id: int, payload: EmployeeUpdate):
    """Update employee details. Frontend: admin picks employee from a
    dropdown (populated via GET /employees/), then submits only the
    changed fields here."""
    update_data = {k: v for k, v in payload.model_dump().items() if v is not None}
    if not update_data:
        raise HTTPException(status_code=400, detail="No fields provided to update")

    result = (
        supabase.table("employees")
        .update(update_data)
        .eq("employee_id", employee_id)
        .execute()
    )
    if not result.data:
        raise HTTPException(status_code=404, detail="Employee not found")
    return result.data[0]


@router.delete("/{employee_id}")
def delete_employee(employee_id: int):
    """Delete employee. Frontend: admin picks employee from a dropdown,
    confirms, then calls this endpoint."""
    result = (
        supabase.table("employees")
        .delete()
        .eq("employee_id", employee_id)
        .execute()
    )
    if not result.data:
        raise HTTPException(status_code=404, detail="Employee not found")
    return {"message": f"Employee {employee_id} deleted successfully"}
